//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SachkoKursovaya
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        public int id { get; set; }
        public Nullable<int> RoomsCount { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Cost { get; set; }
        public string City { get; set; }
        public Nullable<int> LivingSpace { get; set; }
        public Nullable<int> Floor { get; set; }
        public string ApartmentsPhoto { get; set; }
        public Nullable<int> OwnerId { get; set; }
    
        public virtual Owners Owners { get; set; }
    }
}
